
Traceback (most recent call last):
  File "/home/jc0424057/line-bot-tutorial-master/app.py", line 526, in <module>
    app.run(host='linebot.nkfuststudents.cf', port=443, ssl_context=context, threaded=True, debug=True)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 691, in run_simple
    s.bind((hostname, port))
PermissionError: [Errno 13] Permission denied
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/jc0424057/line-bot-tutorial-master/app.py", line 526, in <module>
    app.run(host='linebot.nkfuststudents.cf', port=443, ssl_context=context, threaded=True, debug=True)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 691, in run_simple
    s.bind((hostname, port))
PermissionError: [Errno 13] Permission denied
71.6.202.198 - - [23/Nov/2017 01:06:22] "GET /xxbb HTTP/1.1" 404 -
123.163.114.236 - - [23/Nov/2017 04:34:19] "GET /current_config/passwd HTTP/1.1" 404 -
--------------------------------------------------------------------------------
INFO in app [/home/jc0424057/line-bot-tutorial-master/app.py:42]:
Request body: {"events":[{"type":"message","replyToken":"86a80d5c9940410097273ace05ef56a7","source":{"userId":"Uab52ed589f74408dfcbaf19f04f13132","type":"user"},"timestamp":1511401398186,"message":{"type":"text","id":"7031736756578","text":"."}}]}
--------------------------------------------------------------------------------
203.104.146.157 - - [23/Nov/2017 09:31:07] "POST /callback HTTP/1.1" 200 -
